# Generated by Django 2.2.17 on 2021-01-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210105_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bal_super',
            field=models.CharField(default=610, max_length=200, verbose_name='יתרה סופר'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='exp_super',
            field=models.CharField(default=0, max_length=200, verbose_name='סכום הוצאה לסופר. *הוספת תקציב תתבצע במינוס, לדוגמא -610'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='text1',
            field=models.TextField(verbose_name='מידע נוסף 1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='סכום הוצאה להשלמות. *הוספת תקציב תתבצע במינוס, לדוגמא -215'),
        ),
    ]
